name: dotnet_core
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - name: Build DotNet
        run: |
              dotnet restore ./src/
              dotnet build ./src/ -m --no-restore --no-self-contained --configuration Release --output artifacts_build/
